export { default as ArrowDown } from "./arrowDown.svg";
export { default as ArrowRight } from "./arrowRight.svg";
export { default as ArrowUp } from "./arrowUp.svg";
export { default as EmailIcon } from "./emailIcon.svg";
export { default as InstagramLogo } from "./InstagramLogo.svg";
export { default as LeftArrowIcon } from "./leftArrowIcon.svg";
export { default as LogoIcon } from "./logoIcon.svg";
export { default as SmallArrowDown } from "./smallArrowDown.svg";
export { default as SmallArrowUp } from "./smallArrowUp.svg";
